### ISSUE TITLE
Remove hard-coded version text from glelogo.gle file? (optional suggestion).

### ISSUE THREAD

**Issue by porteusconf** [vlabella/gle-manual#1]
When I run `make all`, title.tex automatically picks the current version for the title page with line `:{\huge GLE \gleversion{}}`

So  for example I see "GLE 4.3.3" as shown in screenshot. But the logo is hard-coded as `text v4.2` in `gle-manual/title/glelogo.gle` which is confusing. I did not look into having glelogo.gle get current version, as I don't know gle well enough yet ;-)  Then I started to think it might be best to just remove the version number from the logo completely, by deleting `! version number` section in `glelogo.gle` file.   
```
!
! version number
!
amove 9.4 1.8
gsave
set hei 1.0
set just bl
set color gray40
text v4.2
grestore
```
When I got rid of all the above lines, it seems to have no problems creating a logo without the version text, so should someone submit a pull request to remove these lines? Currently, with the lines left in, I see "v4.2" above "GLE 4.3.3"
![gle-logo-version-mismatch](https://user-images.githubusercontent.com/58613774/192869766-d1887291-4fcc-48be-94c9-b2ee30b3e2f7.png)

**Comment by vlabella** [comment]
I think that is a good idea to drop the version number from the logo.  I can easily make that change – no need to do a pull request.  There are a couple of typos in the manual and I will post and update soon.

Thanks

Vince


From: porteusconf ***@***.***>
Sent: Wednesday, September 28, 2022 3:38 PM
To: vlabella/gle-manual ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vlabella/gle-manual] Remove hard-coded version text from glelogo.gle file? (optional suggestion). (Issue #1)


When I run make all, title.tex automatically picks the current version for the title page with line :{\huge GLE \gleversion{}}

So for example I see "GLE 4.3.3" as shown in screenshot. But the logo is hard-coded as text v4.2 in gle-manual/title/glelogo.gle which is confusing. I did not look into having glelogo.gle get current version, as I don't know gle well enough yet ;-) Then I started to think it might be best to just remove the version number from the logo completely, by deleting ! version number section in glelogo.gle file.

!

! version number

!

amove 9.4 1.8

gsave

set hei 1.0

set just bl

set color gray40

text v4.2

grestore

When I got rid of all the above lines, it seems to have no problems creating a logo without the version text, so should someone submit a pull request to remove these lines? Currently, with the lines left in, I see "v4.2" above "GLE 4.3.3"
[gle-logo-version-mismatch]<https://user-images.githubusercontent.com/58613774/192869766-d1887291-4fcc-48be-94c9-b2ee30b3e2f7.png>
