### ISSUE TITLE
README.md claims this manual is bundled with GLE but it isn't

### ISSUE THREAD

**Issue by ryandesign** [vlabella/gle-manual#3]
README.md says

> This manual comes bundled with the GLE distribution.

but it doesn't.

**Comment by ryandesign** [comment]
My confusion stemmed from the lack of specificity in the term "distribution". It does not come bundled with the GLE *source* distribution but it may come with a GLE *binary* distribution, provided the creator of the binary distribution was aware that they needed to download this repository separately and tell the GLE build to incorporate it.

**Comment by vlabella** [comment]
It comes bundled with the GLE binary distributions/installers created using cpack.  There is a workflow now in GLE that creates these installers.
